force-app/main/default/objects/Clinic__c/Clinic__c.object-meta.xml
<CustomObject>
    <description>Stores information about healthcare facilities where drugs are stocked, prescriptions are issued, and medications are dispensed.</description>
    <label>Clinic</label>
    <nameField>
        <label>Clinic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinic__c/fields/Open_For_Business__c.field-meta.xml
<CustomField>
    <fullName>Open_For_Business__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open For Business</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Maintains records of licensed healthcare providers, including licensing information and their associated clinic for prescription management.</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/License_Expiry__c.field-meta.xml
<CustomField>
    <fullName>License_Expiry__c</fullName>
    <label>License Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>Enter the license number in the format LIC-######</inlineHelpText>
    <label>License Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Licensed__c.field-meta.xml
<CustomField>
    <fullName>Licensed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Licensed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>General Medicine</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {
    public static Clinic__c createClinic(Boolean openForBusiness){
        Clinic__c newClinic = new Clinic__c(
            Name = 'Apollo Clinic',
        Region__c = 'East',
        Open_For_Business__c = openForBusiness
            );
        
        return newClinic;
    }
    
    public static Doctor__c createDoctor(Id clinicId) {
        
        Doctor__c doctor = new Doctor__c(
            Name = 'Dr. Strange',
        Clinic__c = clinicId,
        Licensed__c = true,
        License_Number__c = 'LIC-100000',
        License_Expiry__c = Date.today().addYears(2),
        Specialization__c = 'General Medicine'
            );
        
        return doctor;
    }
}