force-app/main/default/objects/Clinic__c/Clinic__c.object-meta.xml
<CustomObject>
    <description>Stores information about healthcare facilities where drugs are stocked, prescriptions are issued, and medications are dispensed.</description>
    <label>Clinic</label>
    <nameField>
        <label>Clinic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinic__c/fields/Open_For_Business__c.field-meta.xml
<CustomField>
    <fullName>Open_For_Business__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open For Business</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Maintains records of licensed healthcare providers, including licensing information and their associated clinic for prescription management.</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/services/DoctorService.cls
public with sharing class DoctorService {
    public static void openForBusinessValidation(List<Doctor__c> newDoctors) {
        Set<Id> clinicIds = new Set<Id>();
        for(Doctor__c dr: newDoctors){
            if(dr.Clinic__c!=null){
                clinicIds.add(dr.Clinic__c);
            }
        }
        if(clinicIds.isEmpty()){
            return;
        }
        Map<Id, Clinic__c> clinicMap = new Map<Id, Clinic__c>(
            [SELECT Id, Open_For_Business__c FROM Clinic__c
            WHERE Id IN :clinicIds]
            );
        
        for (Doctor__c dr : newDoctors) {
            if (dr.Clinic__c == null || !clinicMap.containsKey(dr.Clinic__c)) {
                continue;
            }

            Clinic__c clinic = clinicMap.get(dr.Clinic__c);
            
            if (!clinic.Open_For_Business__c) {
                dr.Clinic__c.addError('Doctors cannot be assigned to a clinic that is not open for business.');
            }
        }
    }
}