force-app/main/default/objects/Clinic__c/Clinic__c.object-meta.xml
<CustomObject>
    <description>Stores information about healthcare facilities where drugs are stocked, prescriptions are issued, and medications are dispensed.</description>
    <label>Clinic</label>
    <nameField>
        <label>Clinic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinic__c/fields/Open_For_Business__c.field-meta.xml
<CustomField>
    <fullName>Open_For_Business__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open For Business</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dispense__c/Dispense__c.object-meta.xml
<CustomObject>
    <label>Dispense</label>
    <nameField>
        <displayFormat>DISP-{0000}</displayFormat>
        <label>Dispense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispense__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Dispenses</relationshipLabel>
    <relationshipName>Dispenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Dispensed_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispensed_Date__c</fullName>
    <label>Dispensed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Drug Batches</relationshipLabel>
    <relationshipName>DR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Prescription__c.field-meta.xml
<CustomField>
    <fullName>Prescription__c</fullName>
    <label>Prescription</label>
    <referenceTo>Prescription__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drug_Batch__c/Drug_Batch__c.object-meta.xml
<CustomObject>
    <label>Drug Batch</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Drug Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drug Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <label>Batch Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Quarantined</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Is_Frozen__c.field-meta.xml
<CustomField>
    <fullName>Is_Frozen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Frozen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PRSC-{0000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Dispensed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/lwc/inventoryDashboard/classes/InventoryDashboardController.cls
public with sharing class InventoryDashboardController {
    public class DashboardData {
        @AuraEnabled public Integer totalInventory;
        @AuraEnabled public Integer lowStock;
        @AuraEnabled public Integer frozenInventory;

        @AuraEnabled public Integer totalPatients;
        @AuraEnabled public Integer activePatients;
        @AuraEnabled public Integer activePresc;

        @AuraEnabled public Integer totalDispense;
        @AuraEnabled public Integer dispensedThisMonth;

        @AuraEnabled public Integer totalBatches;
        @AuraEnabled public Integer activeBatches;
        @AuraEnabled public Integer activeClinics;
    }

    public static Integer getDashboardValue(List<AggregateResult> aggregateResults){
        Integer value = (Integer)aggregateResults[0].get('total');
        return value;
    }

    @AuraEnabled(cacheable=true)
    public static DashboardData getDashboardData() {
        DashboardData data=new DashboardData();
        data.totalInventory = getDashboardValue([
        SELECT COUNT(Id) total
        FROM Inventory__c
        ]);

        data.lowStock= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Inventory__c
            WHERE Quantity_On_Hand__c <=10
        ]);

        data.frozenInventory= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Inventory__c
            WHERE Is_Frozen__c=true
        ]);

        data.totalPatients= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Patient__c
        ]);

        data.activePatients= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Patient__c
            WHERE Status__c = 'Active'
        ]);

        data.activePresc= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Prescription__c
            WHERE Patient__r.Status__c = 'Active'
        ]);

        data.totalDispense= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Dispense__c
        ]);

        data.dispensedThisMonth= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Dispense__c
            WHERE Dispensed_Date__c = THIS_MONTH
        ]);

        data.totalBatches= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Drug_Batch__c
        ]);

        data.activeBatches= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Drug_Batch__c
            WHERE Batch_Status__c = 'Active'
        ]);

        data.activeClinics= getDashboardValue([
            SELECT COUNT(Id) total
            FROM Clinic__c
            WHERE Open_For_Business__c = true
        ]);
        return data;
    }
}