force-app/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>Stores master information about medications available in the organization, including identification details and regulatory attributes. Each drug can have multiple manufacturing batches.</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/Drug_Batch__c.object-meta.xml
<CustomObject>
    <label>Drug Batch</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Drug Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drug Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Drug Batches</relationshipLabel>
    <relationshipName>DR</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug Name</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Reorder_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Reorder_Threshold__c</fullName>
    <label>Reorder Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/InventoryServiceTest.cls
@isTest
private class InventoryServiceTest {
    @TestSetup
    static void makeData(){
        Drug__c batch = TestDataFactory.createDrug();
        insert batch;
        Drug_Batch__c drugBatch = TestDataFactory.createDrugBatch(batch.Id);
        insert drugBatch;
    }
    
    @isTest
    static void testPositive_inventoryValidations() {
        Drug_Batch__c batch = [
            SELECT Id
            FROM Drug_Batch__c
            LIMIT 1
        ];
        Inventory__c inv = TestDataFactory.createInventory(50, 20, 'Available', batch.Id);
        Test.startTest();
        insert inv;
        Test.stopTest();
        Inventory__c createdInventory = [
            SELECT Id, Quantity_On_Hand__c, Reorder_Threshold__c, Inventory_Status__c, Drug_Batch__c
            FROM Inventory__c
            WHERE Id = :inv.Id];
        
        System.assertEquals(inv.Id, createdInventory.Id);
        System.assertEquals(50, createdInventory.Quantity_On_Hand__c);
        System.assertEquals(20, createdInventory.Reorder_Threshold__c);
        System.assertEquals('Available', createdInventory.Inventory_Status__c);
        System.assertEquals(batch.Id, createdInventory.Drug_Batch__c);
    }
    @isTest
    static void testNegative_inventoryValidations_QuantityOnHand(){
        Drug_Batch__c batch = [
            SELECT Id
            FROM Drug_Batch__c
            LIMIT 1
        ];
        Inventory__c inv = TestDataFactory.createInventory(-4, 20, 'Available', batch.Id);
        Test.startTest();
        try{
            insert inv;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Quantity on hand cannot be less than 0.'));
        }
        Test.stopTest();
    }
    @isTest
    static void testNegative_inventoryValidations_ReorderThreshold() {
        Drug_Batch__c batch = [
            SELECT Id
            FROM Drug_Batch__c
            LIMIT 1
        ];
        
        Inventory__c inv = TestDataFactory.createInventory(
            50, -30, 'Available', batch.Id);
        Test.startTest();
        try{
            insert inv;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Reorder Threshold cannot be less than 0.'));
        }
        Test.stopTest();
    }
    @isTest
    static void testNegative_inventoryValidations_QuantityOnHand_ReorderThresholdCheck(){
        Drug_Batch__c batch = [
            SELECT Id
            FROM Drug_Batch__c
            LIMIT 1
        ];
        Inventory__c inv = TestDataFactory.createInventory(10, 20, 'Available', batch.Id);
        Test.startTest();
        try{
            insert inv;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Reorder Threshold cannot exceed the Quantity on hand.'));
        }
        Test.stopTest();
    }
    
    @isTest
    static void testPositive_inventoryDrugMatch() {
        Drug_Batch__c batch = [
        SELECT Id, Drug__c
        FROM Drug_Batch__c
        LIMIT 1
    ];
        
        Inventory__c inv = TestDataFactory.createInventory(20, 10, 'Available', batch.Id);
        
        Test.startTest();
        insert inv;
        Test.stopTest();
        
        Inventory__c createdInventory = [
        SELECT Drug_Batch__c, Drug_Name__c
        FROM Inventory__c
        WHERE Id = :inv.Id
    ];
        
        System.assertEquals(batch.Id, createdInventory.Drug_Batch__c);
        System.assertEquals(batch.Drug__c, createdInventory.Drug_Name__c);
    }
}