force-app/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>Stores master information about medications available in the organization, including identification details and regulatory attributes. Each drug can have multiple manufacturing batches.</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/Drug_Batch__c.object-meta.xml
<CustomObject>
    <label>Drug Batch</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Drug Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drug Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Drug Batches</relationshipLabel>
    <relationshipName>DR</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug Name</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Reorder_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Reorder_Threshold__c</fullName>
    <label>Reorder Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/services/InventoryService.cls
public with sharing class InventoryService {
    public static void inventoryValidations(List<Inventory__c> newInventory) {
        for(Inventory__c inv : newInventory){
            if(inv.Quantity_On_Hand__c<0){
                inv.Quantity_On_Hand__c.addError('Quantity on hand cannot be less than 0.');
            }
            if(inv.Reorder_Threshold__c<0){
                inv.Reorder_Threshold__c.addError('Reorder Threshold cannot be less than 0.');
            }
            if(inv.Reorder_Threshold__c>inv.Quantity_On_Hand__c){
                inv.Reorder_Threshold__c.addError('Reorder Threshold cannot exceed the Quantity on hand.');
            }
        }
    }
    public static void inventoryDrugMatch(List<Inventory__c> newInventory){
        Set<Id> drugBatchIds = new Set<Id>();
        for(Inventory__c inv: newInventory){
            if(inv.Drug_Batch__c!=null){
                drugBatchIds.add(inv.Drug_Batch__c);
            }
        }
        if(drugBatchIds.isEmpty()){
            return;
        }
        Map<Id, Drug_Batch__c> drugBatchMap = new Map<Id, Drug_Batch__c>(
            [SELECT Drug__c, Drug__r.Name FROM Drug_Batch__c
            WHERE Id in :drugBatchIds]
            );
        
        for (Inventory__c inv : newInventory) {
            if (inv.Drug_Batch__c == null) continue;
            
            Drug_Batch__c batch = drugBatchMap.get(inv.Drug_Batch__c);
            
            if (batch != null) {
                inv.Drug_Name__c = batch.Drug__c;
            }
        }
    }
}