force-app/main/default/objects/Dispense__c/Dispense__c.object-meta.xml
<CustomObject>
    <label>Dispense</label>
    <nameField>
        <displayFormat>DISP-{0000}</displayFormat>
        <label>Dispense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispense__c/fields/Dispensed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Dispensed_Quantity__c</fullName>
    <label>Dispensed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Drug Batches</relationshipLabel>
    <relationshipName>DR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Prescription__c.field-meta.xml
<CustomField>
    <fullName>Prescription__c</fullName>
    <label>Prescription</label>
    <referenceTo>Prescription__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Maintains records of licensed healthcare providers, including licensing information and their associated clinic for prescription management.</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>Stores master information about medications available in the organization, including identification details and regulatory attributes. Each drug can have multiple manufacturing batches.</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/Drug_Batch__c.object-meta.xml
<CustomObject>
    <label>Drug Batch</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Drug Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drug Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drug_Batch__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Drug Batches</relationshipLabel>
    <relationshipName>DR</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Drug_Batch__c.field-meta.xml
<CustomField>
    <fullName>Drug_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Batch</label>
    <referenceTo>Drug_Batch__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PRSC-{0000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Dispensed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/DispenseServiceTest.cls
@isTest
public with sharing class DispenseServiceTest {
    @TestSetup
    static void makeData(){
        Doctor__c doctor = TestDataFactory.createDoctor();
        Drug__c drug = TestDataFactory.createDrug();
        Patient__c patient = TestDataFactory.createPatient('Active');
        insert new List<SObject>{ doctor, drug, patient };
        Drug_Batch__c drugBatch = TestDataFactory.createDrugBatch(drug.Id);
        insert drugBatch;
        Prescription__c prescription = TestDataFactory.createPrescription(doctor.Id, drug.Id, patient.Id, Date.today().addDays(-14));
        insert prescription;
        Inventory__c inventory = TestDataFactory.createInventory(drugBatch.Id);
        insert inventory;
    }
    private static Id getPrescriptionId(){
        return [
            SELECT Id
            FROM Prescription__c
            LIMIT 1
        ].Id;
    }
    private static Id getPatientId() {
        return [
            SELECT Id
            FROM Patient__c
            LIMIT 1
        ].Id;
    }
    private static Id getInventoryId() {
        return [
            SELECT Id
            FROM Inventory__c
            LIMIT 1
        ].Id;
    }
    
    @isTest
    static void TestPositive_baseValidations(){
        Dispense__c dispense = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        50,
        Date.today());
        
        Test.startTest();
        insert dispense;
        Test.stopTest();
        
        Dispense__c insertedDispense = [
            SELECT Id
            FROM Dispense__c
            WHERE Id = :dispense.Id
        ];
        System.assertEquals(dispense.Id, insertedDispense.Id);
    }
    @isTest
    static void TestNegative_baseValidations_dispenseDate(){
        Dispense__c dispense = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        50,
        Date.today().addMonths(1));
        
        Test.startTest();
        try{
            insert dispense;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Dispense Date cannot be in the future.'));
        }
        Test.stopTest();
    }
    @isTest
    static void TestNegative_baseValidations_dispenseQuantity(){
        Dispense__c dispense = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        0,
        Date.today());
        
        Test.startTest();
        try{
            insert dispense;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Dispensed Quantity must be greater than 0.'));
        }
        Test.stopTest();
    }
    @isTest
    static void TestNegative_prescriptionValidations_dateCheck(){
        Dispense__c dispense = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        50,
        Date.today().addMonths(-2));
        
        Test.startTest();
        try{
            insert dispense;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Dispense date cannot be prior to prescription date.'));
        }
        Test.stopTest();
    }
    @isTest
    static void TestNegative_baseValidations_prescriptionStatus(){
        Id prescId = getPrescriptionId();
        Prescription__c prescription = [
            SELECT Id, Status__c
            FROM Prescription__c
            WHERE Id = :prescId
        ];
        prescription.Status__c='Completed';
        update prescription;
        
        Dispense__c dispense = TestDataFactory.createDispense(
            prescription.Id,
        getPatientId(),
        getInventoryId(),
        50,
        Date.today());
        
        Test.startTest();
        try{
            insert dispense;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Dispense cannot be authorized because the selected prescription is not in Pending or Partially Dispensed status.'));
        }
        Test.stopTest();
    }
    @isTest
    static void TestNegative_prescriptionValidations_patientMismatch(){
        Patient__c secondPatient = TestDataFactory.createPatient('Active');
        insert secondPatient;
        Dispense__c dispense = TestDataFactory.createDispense(
            getPrescriptionId(),
        secondPatient.Id,
        getInventoryId(),
        50,
        Date.today());
        
        Test.startTest();
        try{
            insert dispense;
            System.assert(false,'Expected DMLException');
        }catch(DmlException e){
            System.assert(e.getMessage().contains('Selected patient does not match the patient on the prescription.'));
        }
        Test.stopTest();
    }
    @isTest
    static void TestPositive_validateDispenseOverflow(){
        Dispense__c dispense1 = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        20,
        Date.today());
        
        insert dispense1;
        
        Dispense__c dispense2 = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        29,
        Date.today());
        
        Test.startTest();
        insert dispense2;
        Test.stopTest();
        
        AggregateResult ar = [
            SELECT SUM(Dispensed_Quantity__c) total
            FROM Dispense__c
            WHERE Prescription__c = :getPrescriptionId()
        ];
        
        Decimal totalDispensed = (Decimal) ar.get('total');
        
        System.assertEquals(49, totalDispensed);
        Dispense__c insertedDispense = [
                SELECT Id, Prescription__c
                FROM Dispense__c
                WHERE Id = :dispense2.Id
            ];
        System.assertEquals(dispense2.Id, insertedDispense.Id);
        System.assertEquals(49, totalDispensed);
        
    }
    @isTest
    static void TestNegative_validateDispenseOverflow() {
        
        Dispense__c dispense1 = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        24,
        Date.today()
            );
        
        insert dispense1;
        
        Dispense__c dispense2 = TestDataFactory.createDispense(
            getPrescriptionId(),
        getPatientId(),
        getInventoryId(),
        30,
        Date.today()
            );
        
        Test.startTest();
        try {
            insert dispense2;
            System.assert(false, 'Expected DMLException');
        } catch (DmlException e) {
            System.assert(
                e.getMessage().contains(
                'This dispense would exceed the prescribed quantity of 50.'
                )
                );
        }
        Test.stopTest();
    }
}