force-app/main/default/objects/Dispense__c/Dispense__c.object-meta.xml
<CustomObject>
    <label>Dispense</label>
    <nameField>
        <displayFormat>DISP-{0000}</displayFormat>
        <label>Dispense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispense__c/fields/Dispensed_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispensed_Date__c</fullName>
    <label>Dispensed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Dispensed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Dispensed_Quantity__c</fullName>
    <label>Dispensed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispense__c/fields/Prescription__c.field-meta.xml
<CustomField>
    <fullName>Prescription__c</fullName>
    <label>Prescription</label>
    <referenceTo>Prescription__c</referenceTo>
    <relationshipLabel>Dispense</relationshipLabel>
    <relationshipName>Dispense</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Is_Frozen__c.field-meta.xml
<CustomField>
    <fullName>Is_Frozen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Frozen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Reorder_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Reorder_Threshold__c</fullName>
    <label>Reorder Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PRSC-{0000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Prescribed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Prescribed_Quantity__c</fullName>
    <label>Prescribed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Prescription_Date__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Date__c</fullName>
    <label>Prescription Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Dispensed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/DispenseService.cls
public with sharing class DispenseService {
    public static void baseValidations(List<Dispense__c> newDispenses){
        for(Dispense__c disp: newDispenses){
            if(disp.Dispensed_Date__c != null && disp.Dispensed_Date__c > Date.today()){
                disp.Dispensed_Date__c.addError('Dispense Date cannot be in the future.');
            }
            if(disp.Dispensed_Quantity__c<=0){
                disp.Dispensed_Quantity__c.addError('Dispensed Quantity must be greater than 0.');
            }
        }
    }
    public static void prescriptionValidations(List<Dispense__c> newDispenses){
        Set<Id> prescriptionIds = new Set<Id>();
        for(Dispense__c disp: newDispenses){
            if(disp.Prescription__c!=null){
                prescriptionIds.add(disp.Prescription__c);
            }
        }
        if(prescriptionIds.isEmpty()){
            return;
        }
        Map<Id, Prescription__c> prescMap = new Map<Id, Prescription__c>(
            [SELECT Prescribed_Quantity__c, 
            Patient__c, Status__c, Prescription_Date__c FROM Prescription__c WHERE ID in :prescriptionIds]);
        
        for(Dispense__c disp: newDispenses){
            if(disp.Prescription__c==null){
                continue;
            }
            
            Prescription__c pres = prescMap.get(disp.Prescription__c);
            if(pres==null){
                disp.Prescription__c.addError('The selected prescription no longer exists.');
            } else {
                if(pres.Status__c!='Pending' && pres.Status__c!='Partially Dispensed'){
                    disp.Prescription__c.addError('Dispense cannot be authorized because the selected prescription is not in Pending or Partially Dispensed status.');
                }
                if(disp.Dispensed_Date__c!=null && pres.Prescription_Date__c!=null && disp.Dispensed_Date__c<pres.Prescription_Date__c){
                    disp.Dispensed_Date__c.addError('Dispense date cannot be prior to prescription date.');
                }
                if(disp.Patient__c != pres.Patient__c){
                    disp.Patient__c.addError('Selected patient does not match the patient on the prescription.');
                }
            }
        }
    }
    public static void validateDispenseOverflow(List<Dispense__c> newDispenses){
        
        Set<Id> prescriptionIds = new Set<Id>();
        
        for(Dispense__c disp : newDispenses){
            if(disp.Prescription__c != null){
                prescriptionIds.add(disp.Prescription__c);
            }
        }
        
        if(prescriptionIds.isEmpty()){
            return;
        }
        
        Map<Id, Prescription__c> prescMap = new Map<Id, Prescription__c>(
            [SELECT Prescribed_Quantity__c FROM Prescription__c WHERE Id IN :prescriptionIds]);
        
        Map<Id, Decimal> existingDispenseMap = new Map<Id, Decimal>();
        
        for(AggregateResult ar : [ SELECT Prescription__c, SUM(Dispensed_Quantity__c) totalDispensed
            FROM Dispense__c
            WHERE Prescription__c IN :prescriptionIds
            GROUP BY Prescription__c])
        {
            existingDispenseMap.put(
                (Id) ar.get('Prescription__c'),
            (Decimal) ar.get('totalDispensed'));
        }
        
        for(Dispense__c disp : newDispenses){
            
            if(disp.Prescription__c == null || disp.Dispensed_Quantity__c == null){
                continue;
            }
            
            Prescription__c presc = prescMap.get(disp.Prescription__c);
            
            if(presc == null || presc.Prescribed_Quantity__c == null){
                continue;
            }
            
            Decimal totalDispensed = disp.Dispensed_Quantity__c;
            
            if(existingDispenseMap.containsKey(disp.Prescription__c)){
                totalDispensed += existingDispenseMap.get(disp.Prescription__c);
            }
            
            if(totalDispensed > presc.Prescribed_Quantity__c){
                disp.Dispensed_Quantity__c.addError(
                    'This dispense would exceed the prescribed quantity of '
                    + presc.Prescribed_Quantity__c + '.'
                    );
            }
        }
    }
    public static void prescriptionStatusUpdate(List<Dispense__c> newDispenses){
        Set<Id> prescriptionIds = new Set<Id>();
        for(Dispense__c disp: newDispenses){
            if(disp.Prescription__c!=null){
                prescriptionIds.add(disp.Prescription__c);
            }
        }
        if(prescriptionIds.isEmpty()){
            return;
        }
        Map<Id, Prescription__c> prescMap = new Map<Id, Prescription__c>(
            [SELECT Status__c, Prescribed_Quantity__c FROM Prescription__c WHERE ID in :prescriptionIds]);
        Map<Id, Decimal> existingDispenseMap = new Map<Id, Decimal>();
        Map<Id, Prescription__c> prescriptionUpdates = new Map<Id, Prescription__c>();
        
        for(AggregateResult ar: [SELECT SUM(Dispensed_Quantity__c) existingDispense, Prescription__c
                               FROM Dispense__c 
                               WHERE Prescription__c in :prescriptionIds
                               GROUP BY Prescription__c])
        {
            existingDispenseMap.put((Id)ar.get('Prescription__c'),
            (Decimal)ar.get('existingDispense'));
        }
        
        for(Dispense__c disp: newDispenses){
            if(disp.Prescription__c==null){continue;}
            
            Decimal totalDispense=0.0;
            if(existingDispenseMap.get(disp.Prescription__c)!=null && existingDispenseMap.get(disp.Prescription__c)>0)
            {
                totalDispense = existingDispenseMap.get(disp.Prescription__c);
            }
            
            Prescription__c presc = prescMap.get(disp.Prescription__c);
            if(presc.Prescribed_Quantity__c!=null && presc.Status__c!='Completed'){
                if(totalDispense<presc.Prescribed_Quantity__c){
                    prescriptionUpdates.put(
                        disp.Prescription__c, new Prescription__c(Id = disp.Prescription__c, Status__c = 'Partially Dispensed'));
                }
                else if(totalDispense==presc.Prescribed_Quantity__c){
                    prescriptionUpdates.put(
                        disp.Prescription__c, new Prescription__c(Id = disp.Prescription__c, Status__c = 'Completed'));
                }
            }
        }
        
        if(!prescriptionUpdates.isEmpty()){
            update prescriptionUpdates.values();
        }
    }
    
    public static void inventoryQuantityUpdate(List<Dispense__c> newDispenses) {
        
        Set<Id> inventoryIds = new Set<Id>();
        
        for (Dispense__c disp : newDispenses) {
            if (disp.Inventory__c != null) {
                inventoryIds.add(disp.Inventory__c);
            }
        }
        
        if (inventoryIds.isEmpty()) {
            return;
        }
        
        Map<Id, Inventory__c> inventoryMap = new Map<Id, Inventory__c>(
            [
            SELECT Id,
                   Quantity_On_Hand__c
            FROM Inventory__c
            WHERE Id IN :inventoryIds
        ]
            );
        
        // Sum total quantity dispensed per Inventory
        Map<Id, Decimal> quantityDeductionMap = new Map<Id, Decimal>();
        
        for (Dispense__c disp : newDispenses) {
            
            if (disp.Inventory__c == null) {
                continue;
            }
            
            Decimal currentTotal = quantityDeductionMap.containsKey(disp.Inventory__c)
                ? quantityDeductionMap.get(disp.Inventory__c)
                : 0;
            
            quantityDeductionMap.put(disp.Inventory__c, currentTotal + disp.Dispensed_Quantity__c);
        }
        
        List<Inventory__c> inventoryUpdates = new List<Inventory__c>();
        
        for (Id inventoryId : quantityDeductionMap.keySet()) {
            
            Inventory__c inventory = inventoryMap.get(inventoryId);
            
            if (inventory == null) {
                continue;
            }
            
            inventoryUpdates.add(
                new Inventory__c(
                Id = inventoryId,
            Quantity_On_Hand__c =
                inventory.Quantity_On_Hand__c - quantityDeductionMap.get(inventoryId)
                )
                );
        }
        
        if (!inventoryUpdates.isEmpty()) {
            update inventoryUpdates;
        }
    }
    
    public static void inventoryStatusUpdate(List<Dispense__c> newDispenses){
        Set<Id> inventoryIds = new Set<Id>();
        
        for(Dispense__c disp:  newDispenses){
            if(disp.Inventory__c!=null){
                inventoryIds.add(disp.Inventory__c);
            }
        }
        
        if(inventoryIds.isEmpty()){
            return;
        }
        
        Map<Id, Inventory__c> inventoryMap = new Map<Id, Inventory__c>
            ([SELECT Quantity_On_Hand__c, Reorder_Threshold__c, Is_Frozen__c FROM Inventory__c WHERE Id in :inventoryIds]);
        Map<Id, Inventory__c> inventoryUpdateMap = new Map<Id, Inventory__c>();
        
        for(Id index: inventoryIds){
            if(!inventoryMap.containsKey(index)){
                continue;
            }
            Inventory__c inv = inventoryMap.get(index);
            Decimal quantityOnHand = inv.Quantity_On_Hand__c, reorderThresh = inv.Reorder_Threshold__c;
            String status='';
            if (inv.Is_Frozen__c) {
                status = 'Frozen';
            }
            else if (quantityOnHand == 0) {
                status = 'Out of Stock';
            }
            else if (quantityOnHand <= reorderThresh) {
                status = 'Low Stock';
            }
            else {
                status = 'Available';
            }
            inventoryUpdateMap.put(index, new Inventory__c(
                Id = index, Inventory_Status__c = status));
        }

        if(!inventoryUpdateMap.isEmpty()){
                update inventoryUpdateMap.values();
            }
    }
}