force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Maintains records of licensed healthcare providers, including licensing information and their associated clinic for prescription management.</description>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Licensed__c.field-meta.xml
<CustomField>
    <fullName>Licensed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Licensed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>PRSC-{0000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Prescribed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Prescribed_Quantity__c</fullName>
    <label>Prescribed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Prescription_Date__c.field-meta.xml
<CustomField>
    <fullName>Prescription_Date__c</fullName>
    <label>Prescription Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Refills_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Refills_Allowed__c</fullName>
    <label>Refills Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Refills_Used__c.field-meta.xml
<CustomField>
    <fullName>Refills_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Refills Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Dispensed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/PrescriptionService.cls
public with sharing class PrescriptionService {
    public static void dateValidation(List<Prescription__c> newPrescriptions){
        for(Prescription__c p: newPrescriptions){
            if(p.Expiry_Date__c<Date.today()){ //Validate expiry date.
                p.Expiry_Date__c.addError('Expiry Date cannot be in the past.');
            }
        }
    }
    
    public static void defaultPrescriptionValue(List<Prescription__c> newPrescriptions){
        for(Prescription__c p: newPrescriptions){
            if(p.Prescription_Date__c==null){ //Default prescription date to Today.
                p.Prescription_Date__c=Date.today();
            }
            p.Refills_Used__c=0;
        }
    }
    
    public static void validatePrescriptionQuantity(List<Prescription__c> newPrescriptions){
        for(Prescription__c p : newPrescriptions){ //Validate prescription quantity.
            if(p.Prescribed_Quantity__c != null && p.Prescribed_Quantity__c < 0){
                p.Prescribed_Quantity__c.addError('Prescribed quantity cannot be negative.');
            }

            if(p.Prescribed_Quantity__c != null && p.Prescribed_Quantity__c > 1000){
                p.Prescribed_Quantity__c.addError('Prescribed quantity cannot exceed 1000 units.');
            }
        }
    }
    public static void validateRefills(List<Prescription__c> newPrescriptions){
        for(Prescription__c p : newPrescriptions){  //Validate refill used and allowed.
            
            if(p.Refills_Allowed__c != null && p.Refills_Allowed__c < 0){
                p.Refills_Allowed__c.addError('Refills Allowed cannot be negative.');
            }
        }
    }
    
    public static void validatePatientStatus(List<Prescription__c> newPrescriptions){
        Set<Id> patientIds = new Set<Id>();
        for(Prescription__c p: newPrescriptions){ //Validating required patient field to check the present status of patient.
            if(p.Patient__c!=null){
                patientIds.add(p.Patient__c);
            }
        }
        if(patientIds.isEmpty()){
            return;
        }
        Map<Id, Patient__c> patientMap = new Map<Id, Patient__c>([SELECT Name, Status__c FROM Patient__c WHERE Id IN :patientIds]);
        
        for(Prescription__c p: newPrescriptions){
            Patient__c presPatient = patientMap.get(p.Patient__c);
            if(presPatient==null){
                continue;
            }
            String patientName = presPatient.Name!=null?presPatient.Name:'<Invalid Name>';
            String patientState = presPatient.Status__c;
            
            if(patientState!='Active'){
                p.Patient__c.addError('Prescription cannot be created for '+patientState.toLowerCase()+' patient: '+patientName);
            }
        }
    }
    
    public static void validateDoctorLicense(List<Prescription__c> newPrescriptions){
        Set<Id> doctorSet = new Set<Id>();
        for(Prescription__c prsc: newPrescriptions){
            if(prsc.Doctor__c!=null){
                doctorSet.add(prsc.Doctor__c);
            }
        }
        if(doctorSet.isEmpty()){
            return;
        }
        Map<Id, Doctor__c> doctorMap = new Map<Id, Doctor__c>([SELECT	Licensed__c, 
        Name FROM Doctor__c 
        WHERE Id IN :doctorSet]);
        
        for(Prescription__c prsc: newPrescriptions){
            if(prsc.Doctor__c==null){
                continue;
            }
            Doctor__c dct = doctorMap.get(prsc.Doctor__c);
            if(dct!=null && !dct.Licensed__c){
                String dctName = dct.Name!=null?dct.Name:'<Invalid Name>';
                prsc.Doctor__c.addError('Doctor ' +dctName+ ' is not licensed to prescribe medication.');
            }
        }
    }
}